# permissions for end users to view postgresrestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresrestore-viewer-role
rules:
  - apiGroups:
      - sql.tanzu.vmware.com
    resources:
      - postgresrestores
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - sql.tanzu.vmware.com
    resources:
      - postgresrestores/status
    verbs:
      - get
