# permissions for end users to view postgresversionupgrades.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresversionupgrade-viewer-role
rules:
- apiGroups:
  - sql.tanzu.vmware.com
  resources:
  - postgresversionupgrades
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sql.tanzu.vmware.com
  resources:
  - postgresversionupgrades/status
  verbs:
  - get
